export const cities = [
  { id: 1, name: 'Arica', region_id: 1 },
  { id: 2, name: 'Iquique', region_id: 2 },
  { id: 3, name: 'Antofagasta', region_id: 3 },
  { id: 4, name: 'Copiapó', region_id: 4 },
  { id: 5, name: 'La Serena', region_id: 5 },
  { id: 6, name: 'Valparaíso', region_id: 6 },
  { id: 7, name: 'Santiago', region_id: 7 },
  { id: 8, name: 'Rancagua', region_id: 8 },
  { id: 9, name: 'Talca', region_id: 9 },
  { id: 10, name: 'Chillán', region_id: 10 },
  { id: 11, name: 'Concepción', region_id: 11 },
  { id: 12, name: 'Temuco', region_id: 12 },
  { id: 13, name: 'Valdivia', region_id: 13 },
  { id: 14, name: 'Puerto Montt', region_id: 14 },
  { id: 15, name: 'Coyhaique', region_id: 15 },
  { id: 16, name: 'Punta Arenas', region_id: 16 },
];
