export const communes = [
  { id: 1, name: 'Arica', city_id: 1 },
  { id: 2, name: 'Camarones', city_id: 1 },
  { id: 3, name: 'General Lagos', city_id: 1 },
  { id: 4, name: 'Putre', city_id: 1 },

  { id: 5, name: 'Alto Hospicio', city_id: 2 },
  { id: 6, name: 'Camiña', city_id: 2 },
  { id: 7, name: 'Colchane', city_id: 2 },
  { id: 8, name: 'Huara', city_id: 2 },
  { id: 9, name: 'Iquique', city_id: 2 },
  { id: 10, name: 'Pica', city_id: 2 },
  { id: 11, name: 'Pozo Almonte', city_id: 2 },

  { id: 12, name: 'Antofagasta', city_id: 3 },
  { id: 13, name: 'Calama', city_id: 3 },
  { id: 14, name: 'María Elena', city_id: 3 },
  { id: 15, name: 'Mejillones', city_id: 3 },
  { id: 16, name: 'Ollagüe', city_id: 3 },
  { id: 17, name: 'San Pedro de Atacama', city_id: 3 },
  { id: 18, name: 'Sierra Gorda', city_id: 3 },
  { id: 19, name: 'Taltal', city_id: 3 },
  { id: 20, name: 'Tocopilla', city_id: 3 },

  { id: 21, name: 'Alto del Carmen', city_id: 4 },
  { id: 22, name: 'Caldera', city_id: 4 },
  { id: 23, name: 'Chañaral', city_id: 4 },
  { id: 24, name: 'Copiapó', city_id: 4 },
  { id: 25, name: 'Diego de Almagro', city_id: 4 },
  { id: 26, name: 'Freirina', city_id: 4 },
  { id: 27, name: 'Huasco', city_id: 4 },
  { id: 28, name: 'Tierra Amarilla', city_id: 4 },
  { id: 29, name: 'Vallenar', city_id: 4 },

  { id: 30, name: 'Andacollo', city_id: 5 },
  { id: 31, name: 'Canela', city_id: 5 },
  { id: 32, name: 'Combarbalá', city_id: 5 },
  { id: 33, name: 'Coquimbo', city_id: 5 },
  { id: 34, name: 'Illapel', city_id: 5 },
  { id: 35, name: 'La Higuera', city_id: 5 },
  { id: 36, name: 'La Serena', city_id: 5 },
  { id: 37, name: 'Los Vilos', city_id: 5 },
  { id: 38, name: 'Monte Patria', city_id: 5 },
  { id: 39, name: 'Ovalle', city_id: 5 },
  { id: 40, name: 'Paiguano', city_id: 5 },
  { id: 41, name: 'Punitaqui', city_id: 5 },
  { id: 42, name: 'Río Hurtado', city_id: 5 },
  { id: 43, name: 'Salamanca', city_id: 5 },
  { id: 44, name: 'Vicuña', city_id: 5 },

  { id: 45, name: 'Algarrobo', city_id: 6 },
  { id: 46, name: 'Cabildo', city_id: 6 },
  { id: 47, name: 'Calera', city_id: 6 },
  { id: 48, name: 'Calle Larga', city_id: 6 },
  { id: 49, name: 'Cartagena', city_id: 6 },
  { id: 50, name: 'Casablanca', city_id: 6 },
  { id: 51, name: 'Catemu', city_id: 6 },
  { id: 52, name: 'Concón', city_id: 6 },
  { id: 53, name: 'El Quisco', city_id: 6 },
  { id: 54, name: 'El Tabo', city_id: 6 },
  { id: 55, name: 'Hijuelas', city_id: 6 },
  { id: 56, name: 'Isla de Pascua', city_id: 6 },
  { id: 57, name: 'Juan Fernández', city_id: 6 },
  { id: 58, name: 'La Calera', city_id: 6 },
  { id: 59, name: 'La Cruz', city_id: 6 },
  { id: 60, name: 'La Ligua', city_id: 6 },
  { id: 61, name: 'Limache', city_id: 6 },
  { id: 62, name: 'Llaillay', city_id: 6 },
  { id: 63, name: 'Los Andes', city_id: 6 },
  { id: 64, name: 'Nogales', city_id: 6 },
  { id: 65, name: 'Olmué', city_id: 6 },
  { id: 66, name: 'Panquehue', city_id: 6 },
  { id: 67, name: 'Papudo', city_id: 6 },
  { id: 68, name: 'Petorca', city_id: 6 },
  { id: 69, name: 'Puchuncaví', city_id: 6 },
  { id: 70, name: 'Putaendo', city_id: 6 },
  { id: 71, name: 'Quillota', city_id: 6 },
  { id: 72, name: 'Quilpué', city_id: 6 },
  { id: 73, name: 'Quintero', city_id: 6 },
  { id: 74, name: 'Rinconada', city_id: 6 },
  { id: 75, name: 'San Antonio', city_id: 6 },
  { id: 76, name: 'San Esteban', city_id: 6 },
  { id: 77, name: 'San Felipe', city_id: 6 },
  { id: 78, name: 'Santa María', city_id: 6 },
  { id: 79, name: 'Santo Domingo', city_id: 6 },
  { id: 80, name: 'Valparaíso', city_id: 6 },
  { id: 81, name: 'Villa Alemana', city_id: 6 },
  { id: 82, name: 'Viña del Mar', city_id: 6 },
  { id: 83, name: 'Zapallar', city_id: 6 },

  { id: 84, name: 'Alhué', city_id: 7 },
  { id: 85, name: 'Buin', city_id: 7 },
  { id: 86, name: 'Calera de Tango', city_id: 7 },
  { id: 87, name: 'Cerrillos', city_id: 7 },
  { id: 88, name: 'Cerro Navia', city_id: 7 },
  { id: 89, name: 'Colina', city_id: 7 },
  { id: 90, name: 'Conchalí', city_id: 7 },
  { id: 91, name: 'Curacaví', city_id: 7 },
  { id: 92, name: 'El Bosque', city_id: 7 },
  { id: 93, name: 'El Monte', city_id: 7 },
  { id: 94, name: 'Estación Central', city_id: 7 },
  { id: 95, name: 'Huechuraba', city_id: 7 },
  { id: 96, name: 'Independencia', city_id: 7 },
  { id: 97, name: 'Isla de Maipo', city_id: 7 },
  { id: 98, name: 'La Cisterna', city_id: 7 },
  { id: 99, name: 'La Florida', city_id: 7 },
  { id: 100, name: 'La Granja', city_id: 7 },
  { id: 101, name: 'Lampa', city_id: 7 },
  { id: 102, name: 'La Pintana', city_id: 7 },
  { id: 103, name: 'La Reina', city_id: 7 },
  { id: 104, name: 'Las Condes', city_id: 7 },
  { id: 105, name: 'Lo Barnechea', city_id: 7 },
  { id: 106, name: 'Lo Espejo', city_id: 7 },
  { id: 107, name: 'Lo Prado', city_id: 7 },
  { id: 108, name: 'Macul', city_id: 7 },
  { id: 109, name: 'Maipú', city_id: 7 },
  { id: 110, name: 'María Pinto', city_id: 7 },
  { id: 111, name: 'Melipilla', city_id: 7 },
  { id: 112, name: 'Ñuñoa', city_id: 7 },
  { id: 113, name: 'Padre Hurtado', city_id: 7 },
  { id: 114, name: 'Paine', city_id: 7 },
  { id: 115, name: 'Pedro Aguirre Cerda', city_id: 7 },
  { id: 116, name: 'Peñaflor', city_id: 7 },
  { id: 117, name: 'Peñalolén', city_id: 7 },
  { id: 118, name: 'Pirque', city_id: 7 },
  { id: 119, name: 'Providencia', city_id: 7 },
  { id: 120, name: 'Pudahuel', city_id: 7 },
  { id: 121, name: 'Puente Alto', city_id: 7 },
  { id: 122, name: 'Quilicura', city_id: 7 },
  { id: 123, name: 'Quinta Normal', city_id: 7 },
  { id: 124, name: 'Recoleta', city_id: 7 },
  { id: 125, name: 'Renca', city_id: 7 },
  { id: 126, name: 'San Bernardo', city_id: 7 },
  { id: 127, name: 'San Joaquín', city_id: 7 },
  { id: 128, name: 'San José de Maipo', city_id: 7 },
  { id: 129, name: 'San Miguel', city_id: 7 },
  { id: 130, name: 'San Pedro', city_id: 7 },
  { id: 131, name: 'San Ramón', city_id: 7 },
  { id: 132, name: 'Santiago', city_id: 7 },
  { id: 133, name: 'Talagante', city_id: 7 },
  { id: 134, name: 'Tiltil', city_id: 7 },
  { id: 135, name: 'Vitacura', city_id: 7 },

  { id: 136, name: 'Chépica', city_id: 8 },
  { id: 137, name: 'Chimbarongo', city_id: 8 },
  { id: 138, name: 'Codegua', city_id: 8 },
  { id: 139, name: 'Coinco', city_id: 8 },
  { id: 140, name: 'Coltauco', city_id: 8 },
  { id: 141, name: 'Doñihue', city_id: 8 },
  { id: 142, name: 'Graneros', city_id: 8 },
  { id: 143, name: 'La Estrella', city_id: 8 },
  { id: 144, name: 'Las Cabras', city_id: 8 },
  { id: 145, name: 'Litueche', city_id: 8 },
  { id: 146, name: 'Lolol', city_id: 8 },
  { id: 147, name: 'Machalí', city_id: 8 },
  { id: 148, name: 'Malloa', city_id: 8 },
  { id: 149, name: 'Marchihue', city_id: 8 },
  { id: 150, name: 'Mostazal', city_id: 8 },
  { id: 151, name: 'Nancagua', city_id: 8 },
  { id: 152, name: 'Navidad', city_id: 8 },
  { id: 153, name: 'Olivar', city_id: 8 },
  { id: 154, name: 'Palmilla', city_id: 8 },
  { id: 155, name: 'Paredones', city_id: 8 },
  { id: 156, name: 'Peralillo', city_id: 8 },
  { id: 157, name: 'Peumo', city_id: 8 },
  { id: 158, name: 'Pichidegua', city_id: 8 },
  { id: 159, name: 'Pichilemu', city_id: 8 },
  { id: 160, name: 'Placilla', city_id: 8 },
  { id: 161, name: 'Pumanque', city_id: 8 },
  { id: 162, name: 'Quinta de Tilcoco', city_id: 8 },
  { id: 163, name: 'Rancagua', city_id: 8 },
  { id: 164, name: 'Rengo', city_id: 8 },
  { id: 165, name: 'Requínoa', city_id: 8 },
  { id: 166, name: 'San Fernando', city_id: 8 },
  { id: 167, name: 'Santa Cruz', city_id: 8 },
  { id: 168, name: 'San Vicente de Tagua Tagua', city_id: 8 },

  { id: 169, name: 'Cauquenes', city_id: 9 },
  { id: 170, name: 'Chanco', city_id: 9 },
  { id: 171, name: 'Colbún', city_id: 9 },
  { id: 172, name: 'Constitución', city_id: 9 },
  { id: 173, name: 'Curepto', city_id: 9 },
  { id: 174, name: 'Curicó', city_id: 9 },
  { id: 175, name: 'Empedrado', city_id: 9 },
  { id: 176, name: 'Hualañé', city_id: 9 },
  { id: 177, name: 'Licantén', city_id: 9 },
  { id: 178, name: 'Linares', city_id: 9 },
  { id: 179, name: 'Longaví', city_id: 9 },
  { id: 180, name: 'Maule', city_id: 9 },
  { id: 181, name: 'Molina', city_id: 9 },
  { id: 182, name: 'Parral', city_id: 9 },
  { id: 183, name: 'Pelarco', city_id: 9 },
  { id: 184, name: 'Pelluhue', city_id: 9 },
  { id: 185, name: 'Pencahue', city_id: 9 },
  { id: 186, name: 'Rauco', city_id: 9 },
  { id: 187, name: 'Retiro', city_id: 9 },
  { id: 188, name: 'Río Claro', city_id: 9 },
  { id: 189, name: 'Romeral', city_id: 9 },
  { id: 190, name: 'Sagrada Familia', city_id: 9 },
  { id: 191, name: 'San Clemente', city_id: 9 },
  { id: 192, name: 'San Javier', city_id: 9 },
  { id: 193, name: 'San Rafael', city_id: 9 },
  { id: 194, name: 'Talca', city_id: 9 },
  { id: 195, name: 'Teno', city_id: 9 },
  { id: 196, name: 'Vichuquén', city_id: 9 },
  { id: 197, name: 'Villa Alegre', city_id: 9 },
  { id: 198, name: 'Yerbas Buenas', city_id: 9 },

  { id: 199, name: 'Bulnes', city_id: 10 },
  { id: 200, name: 'Chillán', city_id: 10 },
  { id: 201, name: 'Chillán Viejo', city_id: 10 },
  { id: 202, name: 'Cobquecura', city_id: 10 },
  { id: 203, name: 'Coelemu', city_id: 10 },
  { id: 204, name: 'Coihueco', city_id: 10 },
  { id: 205, name: 'El Carmen', city_id: 10 },
  { id: 206, name: 'Ninhue', city_id: 10 },
  { id: 207, name: 'Ñiquén', city_id: 10 },
  { id: 208, name: 'Pemuco', city_id: 10 },
  { id: 209, name: 'Pinto', city_id: 10 },
  { id: 210, name: 'Portezuelo', city_id: 10 },
  { id: 211, name: 'Quillón', city_id: 10 },
  { id: 212, name: 'Quirihue', city_id: 10 },
  { id: 213, name: 'Ránquil', city_id: 10 },
  { id: 214, name: 'San Carlos', city_id: 10 },
  { id: 215, name: 'San Fabián', city_id: 10 },
  { id: 216, name: 'San Ignacio', city_id: 10 },
  { id: 217, name: 'San Nicolás', city_id: 10 },
  { id: 218, name: 'Treguaco', city_id: 10 },
  { id: 219, name: 'Yungay', city_id: 10 },

  { id: 220, name: 'Alto Biobío', city_id: 11 },
  { id: 221, name: 'Antuco', city_id: 11 },
  { id: 222, name: 'Arauco', city_id: 11 },
  { id: 223, name: 'Cabrero', city_id: 11 },
  { id: 224, name: 'Cañete', city_id: 11 },
  { id: 225, name: 'Chiguayante', city_id: 11 },
  { id: 226, name: 'Concepción', city_id: 11 },
  { id: 227, name: 'Contulmo', city_id: 11 },
  { id: 228, name: 'Coronel', city_id: 11 },
  { id: 229, name: 'Curanilahue', city_id: 11 },
  { id: 230, name: 'Florida', city_id: 11 },
  { id: 231, name: 'Hualpén', city_id: 11 },
  { id: 232, name: 'Hualqui', city_id: 11 },
  { id: 233, name: 'Laja', city_id: 11 },
  { id: 234, name: 'Lebu', city_id: 11 },
  { id: 235, name: 'Los Álamos', city_id: 11 },
  { id: 236, name: 'Los Ángeles', city_id: 11 },
  { id: 237, name: 'Lota', city_id: 11 },
  { id: 238, name: 'Mulchén', city_id: 11 },
  { id: 239, name: 'Nacimiento', city_id: 11 },
  { id: 240, name: 'Negrete', city_id: 11 },
  { id: 241, name: 'Penco', city_id: 11 },
  { id: 242, name: 'Quilaco', city_id: 11 },
  { id: 243, name: 'Quilleco', city_id: 11 },
  { id: 244, name: 'San Pedro de la Paz', city_id: 11 },
  { id: 245, name: 'San Rosendo', city_id: 11 },
  { id: 246, name: 'Santa Bárbara', city_id: 11 },
  { id: 247, name: 'Santa Juana', city_id: 11 },
  { id: 248, name: 'Talcahuano', city_id: 11 },
  { id: 249, name: 'Tirúa', city_id: 11 },
  { id: 250, name: 'Tomé', city_id: 11 },
  { id: 251, name: 'Tucapel', city_id: 11 },
  { id: 252, name: 'Yumbel', city_id: 11 },

  { id: 253, name: 'Angol', city_id: 12 },
  { id: 254, name: 'Carahue', city_id: 12 },
  { id: 255, name: 'Cholchol', city_id: 12 },
  { id: 256, name: 'Collipulli', city_id: 12 },
  { id: 257, name: 'Cunco', city_id: 12 },
  { id: 258, name: 'Curacautín', city_id: 12 },
  { id: 259, name: 'Curarrehue', city_id: 12 },
  { id: 260, name: 'Ercilla', city_id: 12 },
  { id: 261, name: 'Freire', city_id: 12 },
  { id: 262, name: 'Galvarino', city_id: 12 },
  { id: 263, name: 'Gorbea', city_id: 12 },
  { id: 264, name: 'Lautaro', city_id: 12 },
  { id: 265, name: 'Loncoche', city_id: 12 },
  { id: 266, name: 'Lonquimay', city_id: 12 },
  { id: 267, name: 'Los Sauces', city_id: 12 },
  { id: 268, name: 'Lumaco', city_id: 12 },
  { id: 269, name: 'Melipeuco', city_id: 12 },
  { id: 270, name: 'Nueva Imperial', city_id: 12 },
  { id: 271, name: 'Padre Las Casas', city_id: 12 },
  { id: 272, name: 'Perquenco', city_id: 12 },
  { id: 273, name: 'Pitrufquén', city_id: 12 },
  { id: 274, name: 'Pucón', city_id: 12 },
  { id: 275, name: 'Purén', city_id: 12 },
  { id: 276, name: 'Renaico', city_id: 12 },
  { id: 277, name: 'Saavedra', city_id: 12 },
  { id: 278, name: 'Temuco', city_id: 12 },
  { id: 279, name: 'Teodoro Schmidt', city_id: 12 },
  { id: 280, name: 'Toltén', city_id: 12 },
  { id: 281, name: 'Traiguén', city_id: 12 },
  { id: 282, name: 'Victoria', city_id: 12 },
  { id: 283, name: 'Vilcún', city_id: 12 },
  { id: 284, name: 'Villarrica', city_id: 12 },

  { id: 285, name: 'Corral', city_id: 13 },
  { id: 286, name: 'Futrono', city_id: 13 },
  { id: 287, name: 'Lago Ranco', city_id: 13 },
  { id: 288, name: 'Lanco', city_id: 13 },
  { id: 289, name: 'La Unión', city_id: 13 },
  { id: 290, name: 'Los Lagos', city_id: 13 },
  { id: 291, name: 'Máfil', city_id: 13 },
  { id: 292, name: 'Mariquina', city_id: 13 },
  { id: 293, name: 'Paillaco', city_id: 13 },
  { id: 294, name: 'Panguipulli', city_id: 13 },
  { id: 295, name: 'Río Bueno', city_id: 13 },
  { id: 296, name: 'Valdivia', city_id: 13 },

  { id: 297, name: 'Ancud', city_id: 14 },
  { id: 298, name: 'Calbuco', city_id: 14 },
  { id: 299, name: 'Castro', city_id: 14 },
  { id: 300, name: 'Chaitén', city_id: 14 },
  { id: 301, name: 'Chonchi', city_id: 14 },
  { id: 302, name: 'Cochamó', city_id: 14 },
  { id: 303, name: 'Curaco de Vélez', city_id: 14 },
  { id: 304, name: 'Dalcahue', city_id: 14 },
  { id: 305, name: 'Fresia', city_id: 14 },
  { id: 306, name: 'Frutillar', city_id: 14 },
  { id: 307, name: 'Futaleufú', city_id: 14 },
  { id: 308, name: 'Hualaihué', city_id: 14 },
  { id: 309, name: 'Llanquihue', city_id: 14 },
  { id: 310, name: 'Los Muermos', city_id: 14 },
  { id: 311, name: 'Maullín', city_id: 14 },
  { id: 312, name: 'Osorno', city_id: 14 },
  { id: 313, name: 'Palena', city_id: 14 },
  { id: 314, name: 'Puerto Montt', city_id: 14 },
  { id: 315, name: 'Puerto Octay', city_id: 14 },
  { id: 316, name: 'Puerto Varas', city_id: 14 },
  { id: 317, name: 'Puqueldón', city_id: 14 },
  { id: 318, name: 'Purranque', city_id: 14 },
  { id: 319, name: 'Puyehue', city_id: 14 },
  { id: 320, name: 'Queilén', city_id: 14 },
  { id: 321, name: 'Quellón', city_id: 14 },
  { id: 322, name: 'Quemchi', city_id: 14 },
  { id: 323, name: 'Quinchao', city_id: 14 },
  { id: 324, name: 'Río Negro', city_id: 14 },
  { id: 325, name: 'San Juan de la Costa', city_id: 14 },
  { id: 326, name: 'San Pablo', city_id: 14 },

  { id: 327, name: 'Aysén', city_id: 15 },
  { id: 328, name: 'Chile Chico', city_id: 15 },
  { id: 329, name: 'Cisnes', city_id: 15 },
  { id: 330, name: 'Cochrane', city_id: 15 },
  { id: 331, name: 'Coyhaique', city_id: 15 },
  { id: 332, name: 'Guaitecas', city_id: 15 },
  { id: 333, name: 'Lago Verde', city_id: 15 },
  { id: 334, name: "O'Higgins", city_id: 15 },
  { id: 335, name: 'Río Ibáñez', city_id: 15 },
  { id: 336, name: 'Tortel', city_id: 15 },

  { id: 337, name: 'Antártica', city_id: 16 },
  { id: 338, name: 'Cabo de Hornos', city_id: 16 },
  { id: 339, name: 'Laguna Blanca', city_id: 16 },
  { id: 340, name: 'Natales', city_id: 16 },
  { id: 341, name: 'Porvenir', city_id: 16 },
  { id: 342, name: 'Primavera', city_id: 16 },
  { id: 343, name: 'Punta Arenas', city_id: 16 },
  { id: 344, name: 'Río Verde', city_id: 16 },
  { id: 345, name: 'San Gregorio', city_id: 16 },
  { id: 346, name: 'Timaukel', city_id: 16 },
  { id: 347, name: 'Torres del Paine', city_id: 16 },
];
