export const regions = [
  { id: 1, name: 'Arica y Parinacota', country_id: 1 },
  { id: 2, name: 'Tarapacá', country_id: 1 },
  { id: 3, name: 'Antofagasta', country_id: 1 },
  { id: 4, name: 'Atacama', country_id: 1 },
  { id: 5, name: 'Coquimbo', country_id: 1 },
  { id: 6, name: 'Valparaíso', country_id: 1 },
  { id: 7, name: 'Metropolitana de Santiago', country_id: 1 },
  { id: 8, name: "Libertador General Bernardo O'Higgins", country_id: 1 },
  { id: 9, name: 'Maule', country_id: 1 },
  { id: 10, name: 'Ñuble', country_id: 1 },
  { id: 11, name: 'Biobío', country_id: 1 },
  { id: 12, name: 'La Araucanía', country_id: 1 },
  { id: 13, name: 'Los Ríos', country_id: 1 },
  { id: 14, name: 'Los Lagos', country_id: 1 },
  { id: 15, name: 'Aysén del General Carlos Ibáñez del Campo', country_id: 1 },
  { id: 16, name: 'Magallanes y de la Antártica Chilena', country_id: 1 },
];
